FROM tensorflow/tensorflow:2.9.1-gpu-jupyter

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install --no-install-recommends -y gfortran git metis libmetis-dev curl ca-certificates ssh make \
							python3-pip python3-setuptools gmsh python3-gmsh python3-tqdm \
							python3-sklearn python3-matplotlib libopenmpi-dev openmpi-bin \
							cuda-nvrtc-dev-11-2 libcublas-dev-11-2

RUN pip3 install pygmsh pyfr==1.13.0 tensorflow-io==0.26.0

RUN cd / && git clone https://github.com/aligirayhanozbay/pydscpack/ && cd /pydscpack && pip3 install --user -e .
