FROM ubuntu:jammy

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install --no-install-recommends -y gfortran git libmetis-dev curl libglu1-mesa ca-certificates libarchive-dev libxcursor1 libgl1-mesa-glx ssh

RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && chmod +x Miniconda3-latest-Linux-x86_64.sh && ./Miniconda3-latest-Linux-x86_64.sh -b && eval "$(/root/miniconda3/bin/conda shell.bash hook)" && conda init
ENV PATH=/root/miniconda3/bin:$PATH
RUN conda install -n base conda-forge::mamba
RUN mamba install -y -c conda-forge tensorflow openmpi openmpi-mpicxx gxx_linux-64 gmsh python-gmsh tqdm scikit-learn make matplotlib paraview
RUN pip3 install pygmsh pyfr==1.14.0

RUN cd / && git clone https://github.com/aligirayhanozbay/pydscpack/ && cd /pydscpack && pip3 install -e .
